[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
[tool.hatch.build.targets.wheel]
packages = ["SKD"]
[project]
name = "soul_knight_data_processing"
<<<<<<< HEAD
version = "0.0.8"
=======
version = "0.0.7"
>>>>>>> 8f0ea307e48f0e62b7f7e77f5d089e7d5c054c5c
authors = [
  { name="Roren Natsumi", email="RorenNatsumi@outlook.com"},
]
description = "A package for encode or decode soul_knight data files."
readme = "README.md"
license = { file="LICENSE" }
dependencies = [
        "pycryptodome",
        "requests",
        "wget"
    ]

[project.urls]
"Homepage" = "https://github.com/Suto-Commune/soul_knight/"
